YaLTeR/OpenAG

cl_dll/update_checker.cpp

Fix libcurl file name passed to `dlopen` on macOS.

Fix libcurl lib name for update checker on macOS

---

cl_dll/hud.cpp
cl_dll/view.cpp

Viewroll and viewmodel bob tilt was loved by many players at Half-Life's release but was removed from the engine in version 1.1.1.0. I think that adding this would attract more players to AG as it brings a removed old-school feature back.
Video demonstration:
https://www.youtube.com/watch?v=Yf2YzRkdVOU

Add viewroll and viewmodel bob tilt

---

.github/workflows/CI.yml
README.md

Supersedes #71 due to branch name.
#
No macOS builds since they still fail: https://github.com/Margen67/OpenAG/runs/550373800#step:4:113

Add GitHub Actions CI for Windows and Linux

---

cl_dll/hud.cpp
cl_dll/hud.h
cl_dll/view.cpp

Fixes the height of the first person cam when spectating in games that use the latest HLSDK, like HL.
When playing HL with OpenAG you would have the cam 28 units higher than it should be in First Person spectator mode, which is a bit annoying.
`cl_viewheight_mode 0` - normal AG viewheight
`cl_viewheight_mode 1` - fixed viewheight for HL

Add a cvar to fix viewheight on newer HLSDK

---

cl_dll/hud_spectator.cpp
cl_dll/hud_spectator.h

Valve added some support for multiple overview layers, but it seems that at the end they decided not to support them. So this is mostly refactoring of overview code and completing the support.
Some background on overviews:
- An overview is the top-down view of the map that you can see from spectator mode when pressing `+use`. You can rotate it by moving the mouse, and height (Z) is only taken into account for positioning player indicators or yourself, with a line going from the indicator to the overview image where you can see at which height players are depending on how long is the line. [Example overview image](https://imgur.com/a/3he7Ice).
- An overview is defined in a txt file located in the _overviews_ directory, with the same name as the corresponding map. [Example overview file …

Multilayer overviews

---

cl_dll/entity.cpp
cl_dll/hud.cpp
cl_dll/hud.h

Cvar `cl_fix_standing_corpses ` fixes the issue with standing corpses leaved by players playing with high FPS.
Cvar `cl_hidecorpses `gives you the ability to hide the corpses in case they bother you. If there wasn't a fix for the standing corpses, it becomes useful to counter that issue.

Client: Add cvar to hide corpses and fix standing corpses

---

cl_dll/hud_redraw.cpp

This is useful for creating HLKZ videos.

Make hud_speedometer draw even when hud_draw is 0

---

CMakeLists.txt

Building with GCC 10.2.0 and GNU ld 2.35 on Arch Linux causes a linker warning to appear:
```
[73/73] Linking CXX shared library client.so
/usr/bin/ld: external/discord-rpc/src/libdiscord-rpc.a(rpc_connection.cpp.o): warning: relocation against `_ZNK9rapidjson13GenericReaderINS_4UTF8IcEES2_20FixedLinearAllocatorILj2048EEE12NumberStreamINS_25GenericInsituStringStreamIS2_EELb0ELb0EE4PeekEv' in read-only section `.text._ZN9rapidjson13GenericReaderINS_4UTF8IcEES2_20FixedLinearAllocatorILj2048EEE7ConsumeINS5_12NumberStreamINS_25GenericInsituStringStreamIS2_EELb0ELb0EEEEEbRT_NSB_2ChE[_ZN9rapidjson13GenericReaderINS_4UTF8IcEES2_20FixedLinearAllocatorILj2048EEE7ConsumeINS5_12NumberStreamINS_25GenericInsituStringStreamIS2_EELb0ELb0EEEEEbRT_NSB_2ChE]'
/usr/bin/ld: warning: creating DT_TEXTREL in a …
```

Fix linker relocation warning

---

cl_dll/input.cpp

Adds a command, `+ducktap` which works as an automatic perfect duckroll. 
Also adds a cvar `cl_autojump_priority`, which controls whether ducktap or jump take precedence.

Implement ducktap autofunc

---

cl_dll/hud_spectator.cpp

Spectator overview rendering code expects to have at least one layer (which is added in `CHudSpectator::Reset()`) but rendering can begin before `ResetHUD` message is received by the client and layers are added.
The PR adds a check to `CHudSpectator::DrawOverviewLayer` that skips rendering overview until layers are added.

Fix OOB in spectator overview rendering

---

cl_dll/vgui_ScorePanel.cpp
cl_dll/vgui_ScorePanel.h

Replaces `vgui::TextImage` with `UnicodeTextImage` in scoreboard server name label. This adds Unicode support, anti-aliasing and high-resolution scaling to the server name shown in the scoreboard.
Before (rendered in 4K, downscaled to 1080p):
After:

Add unicode server name to the scoreboard

---

cl_dll/vgui_UnicodeTextImage.cpp

It looks like ABI of virtual classes in anonymous namespaces is different from classes in named namespaces or global namespace. Solved by moving VGUI2 interfaces into `vgui2` namespace.

Fix UnicodeTextImage::createFont crash on Linux

---

cl_dll/vgui_SchemeManager.cpp
cl_dll/vgui_SchemeManager.h
cl_dll/vgui_ScorePanel.cpp
cl_dll/vgui_UnicodeTextImage.cpp

1) Fonts on Linux are created 2px taller than they need to be so I added some code to compensate for that.
2) Widened SteamID column by 4px so long SteamIDs don't get clipped.
3) Font names are now loaded from current scheme file (XXX_textscheme.txt) to allow users to change fonts to different ones.

Scoreboard font fixes

---

cl_dll/view.cpp

This pull request fixes a few issues with `V_FindViewModelByWeaponModel` function.
1. Fix a crash when trying to find a custom model that is not on a hardcoded list.
2. If model was not found on the list (e.g. a custom WeaponMod weapon), it will attempt to convert player model name to a view model name ("models/p_weapon.mdl" -> "models/v_weapon.mdl"). It works most of the time but some weapons on some server use different names for world and view models (e.g. "p_dbarrel.mdl" and "v_dbarrel_hev.mdl"). In that case spectator won't see the view model.
Resolves #93

Fix incorrect handling of custom view models

---

cl_dll/hud.cpp

Flags `default_fov` cvar to be written into the game config so players don't have to hardcode it in the user config.

Save default_fov into the config

---

cl_dll/in_camera.cpp

Hello.
First off, I am proposing this change to the client code, even though I am aware this should mainly be fixed server-side, the motivation for that is that for example Deathmath Classic and Ricochet don't suffer from this problem but also only fix it in the client library.
**Reason for this change/Motivation:**
Thirdperson can at the current state be potentially used to cheat in HLDM/AG without any modifications of the client DLL.
If you are on a maxplayers = 1 & deathmatch 0 server OR you are not connected at all and use these commands in the console:
```
sv_cheats 1
thirdperson // or cam_command 1
```
And then join a multiplayer AG server you will be in thirdperson mode, even though it normally isn't allowed, but the code in HLDM only checks after you type "thirdperson" **WHILE on …

Proposal: Disable thirdperson

---

cl_dll/ammohistory.cpp

Fixed HUD align bug in ammo history for ammo < 10 (#54)

---

cl_dll/hud_spectator.cpp
cl_dll/vgui_SpectatorPanel.cpp

Hello. Useless fixes galore!
This PR fixes a thing that's probably only been bugging me as I am probably the only person to ever try to use the VGUI spectator panel in AG and it always ticked me off that it doesn't work. This is the panel that appears when you press +duck while in spectator mode.
Let's get this out of the way first: spectating while on a server (and not on an HLTV server or on dem_forcehltv 1) is **server-side**, the **client** only sends the server commands when it wants to change the target to spectate / change the mode of spectating etc.
This change has to be made:
```			
sprintf(cmdstring,"spec_mode %i",iNewMainMode );
```
As the server DLL that we are all using implements this client->server cmd as "spec_mode" instead of "specmode", see here: …

Fixed spectator mode VGUI panel

---

cl_dll/StudioModelRenderer.cpp
cl_dll/StudioModelRenderer.h
cl_dll/view.cpp

Hello. This closes #26.
@execut4ble says:
> Something like CSGO's viewmodel_fov so you can set how much your weapon sticks out without changing the actual field of view.
AFAIK CSGO's `viewmodel_fov` doesn't actually change the viewmodel_**FOV** at all, it's merely (I THINK) changing **the origin** from which the "**camera**" is **looking at the gun** (or it's actually just keeping the origin the same, but changing how it's "looked at" some other way, but you get the point).
This is different to what other source games e.g. Portal/HL2/HL2EP1 do, where viewmodel_fov actually changes the FOV for the viewmodel "camera". 
I've **implemented cvars for both cases** (although the CS:GO offset thing isn't exactly like in CS:GO, obv, you'll see what I mean). See the reference screenshots & videos …

Added viewmodel FOV cvar, added viewmodel xyz offset cvar

---

cl_dll/StudioModelRenderer.cpp
cl_dll/StudioModelRenderer.h
cl_dll/view.cpp

Fixes incorrect weapon effect positions (sprites and beams) when viewmodel FOV is different from default. It uses code from Source SDK (c_baseviewmodel.cpp, ::FormatViewModelAttachment) to reproject on-screen position from main view FOV to viewmodel FOV.
I used global variables to save view position and direction vectors since they are not available outside of `V_CalcRefDef`.
Demo:
https://www.youtube.com/watch?v=9_10Oms73Fg

Fix viewmodel attachment positions

---

cl_dll/saytext.cpp

Hello.
This is a thing that bugged me for a while, since I sometimes I really want to copy a chat message immediately (to google translate for example :^), but at the same time I prefer using a hud_saytext_time above 5 seconds for normal chatting. 
This way it won't wait for the ScrollTextUp if `hud_saytext_immediate_print` is set to 1. I also added the archive flag to the **hud_saytext_time** cvar.
Also, is the cvar name alright? Seems a bit long to me, but I can't think of anything descriptive and at the same time shorter. (instant_print? print_instantly? ...)

Add an option to enable printing chat messages to console immediately

---

cl_dll/CMakeLists.txt
cl_dll/hud.cpp
cl_dll/hud.h
cl_dll/hud_customtimer.cpp
cl_dll/hud_customtimer.h

Closes #64. Implemented mostly 1:1 to the the AG 6.6 implementation. I added a bar (and a colon in the text), because I think it looks OK, but this is of course up for discussion, for example if @chortex who originally reported this issue is still around, or any other players that use customtimer in their binds.
I've also decided for showing "Timer: 0" when the time is <1.0 (and 9 when "customtimer 10" starts and number instantly becomes 9.999999) like the original implementation does instead of subtracting and adding 1.
**AG 6.6:**
**OpenAG:**
**GIF:** 
**Video:** 
https://user-images.githubusercontent.com/5108747/119066552-4e282a00-b9e0-11eb-9db7-8e586347dac9.mp4
(The sound like in the original is present I just didn't record it.)
I've also added a check to fail if the time in seconds …

Implement command customtimer

---

.appveyor.yml
.github/workflows/CI.yml

Travis is no longer free*, so another CI like Azure Pipelines or AppVeyor should be added.
GitHub Actions isn't an option for macOS since it doesn't have Xcode 9.4.1. (https://github.com/actions/virtual-environments/issues/2347)
AppVeyor:
* Can easily link to newest build.
Azure Pipelines:
* Faster. (allows more than one build simultaneously)

Add AppVeyor CI for macOS

---

cl_dll/CMakeLists.txt
cl_dll/hud.cpp
cl_dll/hud.h
cl_dll/hud_oldscoreboard.cpp
cl_dll/hud_oldscoreboard.h
cl_dll/hud_redraw.cpp
cl_dll/vgui_TeamFortressViewport.cpp

This closes #89.
Oof, I might finally finish this. 
This is based on the original AG old scoreboard (which is based on the old HL scoreboard).
I've tried to stick as close to the original as I could but at the same time I wanted to improve a few things, one of them being rendering this somewhat accurately and be usable on Linux as well. Therefore I have made some alternative design (positioning mainly) choices. I've also introduced a `cl_oldscoreboard_width` cvar where the motivation was that since the width is already different on Linux, I might as well let the user change it to whatever he wants. Plus this also works out well for the user if the user wants to use a custom HUD font and/or a different size, they can use cl_oldscoreboard_width to make it all fit again.
So yeah, positions …

Implement cl_old_scoreboard

---

cl_dll/hud_redraw.cpp
cl_dll/hud_spectator.cpp

default_fov's value like when playing the game is now used for when the client is only watching a game through a HLTV proxy.
**hud_redraw.cpp:**
* The changes here are for when default_fov is changed while watching
* Commented the hud_redraw.cpp code instead of deleting just so we know that it was there before. 
* * Therefore it just uses the FOV logic in the code above and skips setting it to a constant for HLTV like it originally does.
**hud_spectator.cpp**
* The changes here are used when you connect to a proxy from the game menu before joining any other game after you launch OpenAG.
A thing that probably never bugged anyone, but it sure bugs me.

HLTV: use the client's default_fov value, not 90

---

cl_dll/hud_spectator.cpp

As per Alex's bug report:
> There is just 1 more thing that makes ag6.6 different: you can see your default handgun crosschair @ spectate mode in OpenAG. A lot of peeps use the command r_drawviewmodel 0 so there is no way to understand what the weapon in hand atm.

Use the target player's weapon crosshair when spectating in first person, don't replace it

---

cl_dll/rainbow.cpp

```cpp
int CHud::GetHudStringWidth(const char* string)
{
return gEngfuncs.pfnDrawString(0, 0, string, 0, 0, 0);
}
```
`GetHudStringWidth` gets the string length by drawing it with a black color (due to additive blending mode, it becomes transparent). Rainbow HUD overrides this color, causing the text to become visible.
This PR also fixes a small issue in `DrawStringReverse`. It used to call `DrawString` to get the string width. `DrawString` needs to decode the input string into separate UTF-8 chars to draw them with different colors but it isn't needed in this case. I replaced it with a call to `CHud::GetHudStringWidth`.

Rainbow HUD: Fix invisible text being visible

---

cl_dll/hud_oldscoreboard.cpp

Fixes #119 (that's present on some servers), hopefully. ;-)
**EDIT: Tested by me & @iCHOPPERi on Ironanjuu & `AGHLDM DE #2 | 1000 FPS | FastDL`, seems like this does the trick.** :)

Skip NULL nicknames in the sorted scoreboard in order to get rid of ghost players when they disconnect while +showscores is held

---

cl_dll/StudioModelRenderer.cpp
cl_dll/ev_common.cpp
cl_dll/ev_hldm.cpp
cl_dll/view.cpp

Resolves #128 
Looks like an engine bug (couldn't really find where it happens in Ghidra, but it's pretty obvious seeing as we don't use cl_righthand's *actual* value anywhere in the client code), so not much we can do here other than clamp it.
* ~~Not just using min max (without if statement) since this way it will only be called once.~~
* ~~Resetting the cvar using Cvar_SetValue instead of min maxing the value, because engine is at fault and uses the cvar's value.~~
EDIT: alright yea looks like this is it
```c++
(*qglCullFace)(0x404);
bVar4 = false;
if (((cl_righthand != (cvar_t *)0x0) && (0.0 < cl_righthand->value)) &&
(cl.viewent.index == currententity->index)) {
(*qglDisable)(0xb44);
bVar4 = true;
}
```

Sync up the condition for cl_righthand with the one that's in engine

---

cl_dll/rainbow.cpp

If the game has just started (`gHUD.m_flTime` is low) and x or y are negative, current phase angle in `GetRainbowColor` can become negative. Then `fmod 360`, which returns values in the range (-360; 360), can return a negative number and trigger the assetion in `HSVtoRGB`.
This PR resolves that by adding 360 degrees to fmod result if it's negative.

Rainbow HUD: Fix negative phase

---

cl_dll/StudioModelRenderer.cpp
cl_dll/StudioModelRenderer.h

Hello.
I've seen a lot of people use the edited so-called "HLTV" models where `idle` and `fidget` sequences are set to 1 frame and 1 fps, this does the same thing but without replacing the original (or HD) models. This works on all the default weapons, but probably not on custom added 3rd party server side weapons (not models, i.e. weapons that are not in original HL1), though, unless they use `*fidget*` and `*idle*` in their sequence labels. 
It also doesn't work on any custom weapon models that use different labels for idle / fidget. <- If you think it'd be beneficial if this worked for all custom models including ones that have different labels, I can go ahead and implement it based on indexes of sequences for each gun instead.
**EDIT**: I've had a discussion with @execut4ble and we …

Added cl_viewmodel_disable_idle to disable idle/fidget animations on the viewmodel models

---

cl_dll/CMakeLists.txt
cl_dll/hud.cpp
cl_dll/hud.h
cl_dll/hud_jumpspeed.cpp
cl_dll/hud_jumpspeed.h
cl_dll/view.cpp

Closes #133
Stolen from BXT, based on hud_speedometer.cpp. 
Normal Y pos based on the original BXT (1 "px" above hud_speedometer), for "below cross" I've decided to have it under hud_speedometer for simplicity (i.e. not dynamically moving based on `hud_speedometer_below_cross`'s value)
Not too sure about the `static float`s and what not in the code, so do tell me, if it somehow doesn't make sense here, but does in BXT.
**Video:** 
https://user-images.githubusercontent.com/5108747/123566130-3900a100-d7bf-11eb-88d1-b09b33f0f514.mp4

Add jumpspeed HUD like in BXT

---

cl_dll/GameStudioModelRenderer.h
cl_dll/StudioModelRenderer.cpp
cl_dll/StudioModelRenderer.h
cl_dll/ev_common.cpp
cl_dll/ev_hldm.cpp
cl_dll/eventscripts.h

Fixes a few issues with ejected shells and cl_viewmodel_* cvars.
1. Enabling left-handed mode inverted shell direction for other player models (which hold the weapon world model in the right hand).
2. cl_viewmodel_ofs cvars didn't offset shell spawn positions.
3. Shell positions weren't adjust for cl_viewmodel_fov.

Viewmodel ejected shells fixes

---

cl_dll/in_camera.cpp

Hello. Tried to make the cvar name as close to the dem_forcehltv since it only applies to this (because in a real HLTV demo, the localplayer is the HLTV proxy and therefore all players are rendered correctly) and at the same time not too long.
This is basically this, but client DLL edition: https://github.com/YaLTeR/bxt-rs/issues/10 (https://github.com/advancedfx/advancedfx/blob/main/AfxHookGoldSrc/HltvFix.cpp)
Video:
https://user-images.githubusercontent.com/5108747/129068510-f3c7a689-5bce-4e59-bcf7-3fd655195948.mp4

Always render local player model when watching a POV demo with dem_forcehltv 1

---

README.md

After testing OpenAG in the VS2022 preview, and having confirmed that [it does build on the latest VS2022/C++ 20 compilers,](https://imgur.com/a/2hB4dI6) I thought I'd add the build instructions for it.
~~I've placed it below VS2017 as chances are slim people will want to use pre-release beta software to develop OpenAG; but the instructions are there should they wish to do so. Editors may want to edit it above VS2019 once VS2022 fully releases~~

Add build instructions for Visual Studio 2022 Preview

---

cl_dll/hud.cpp
cl_dll/hud.h
cl_dll/hud_redraw.cpp

Makes HL KreedZ HUDs draw even when hud_draw is 0: ![20210903151618_1](https://user-images.githubusercontent.com/58108407/131997094-f19c116b-d8eb-4023-8e13-9351a3a67765.jpg)

Added a CVAR to draw messages when hud_draw = 0

---

cl_dll/hud_jumpspeed.cpp
cl_dll/hud_jumpspeed.h
cl_dll/hud_speedometer.cpp
cl_dll/hud_speedometer.h

Since previous update changed default speedometer position there are some players (including me) who want to get it back and being able to move it whatever you want in general

Add hud_jumpspeed_height and hud_speedometer_height cvars

---

cl_dll/hud_watermark.cpp

For `playdemo` and normal gameplay the `time` float is correct on the first Draw() frame, this however isn't true for `viewdemo`, where it starts on the correct "server time" from that demo (e.g. `331`) for a few frames, but then resets itself to 0 and starts adding up, this results in the 15 second offset for hiding the watermark message being set to e.g. 331 + 15 = 346, but `time` is then counting from 0, resulting in the watermark not disappearing for 346 more seconds when using `viewdemo`.

Fix watermark not disappearing when playing back demo with viewdemo

---

cl_dll/hud.h
cl_dll/text_message.cpp

With the next version of AG an extra byte will be sent on the TextMsg event. This byte tells what type of message it is. For the moment I have added 2 message types, and I'm planning a few more in the future, like a type for name and/or team changing messages. This makes it possible to ignore certain types of messages easily in the client, without relying on server configuration or checking what kind of text the message has.
This byte will be:
-1: if absent (that's what READ_BYTE() returns if it ran out of bytes to read)
0: if it's a spawn message
1: if it's a damage message
A spawn message is sent as soon as a practice bot respawns, telling the spot number where it spawned.
A damage message tells how much damage you dealt to a practice bot.
New cvars:
- `cl_ignore_spawn_messages` <0/1> - …

Add cvars to ignore certain messages

---

cl_dll/hud.cpp

Allows to show map triggers on a local server, useful for researching without map editors or 3rd-party tools:
https://user-images.githubusercontent.com/58108407/151686645-99e22ec4-320c-47b1-8eb1-1f4db86a5ffa.mp4
In WON era, `showtriggers` been registered on engine side, but with updates later it's been removed, let's get it back now :)
It works cuz there are still some calls to `showtriggers` cmd in the server side, but the command itself is not declared in latest HLSDK:
https://github.com/YaLTeR/OpenAG/blob/061c06cfb5cc0e837c4063aa4dcedd9fe7d286bc/dlls/bmodels.cpp#L267-L268
https://github.com/YaLTeR/OpenAG/blob/061c06cfb5cc0e837c4063aa4dcedd9fe7d286bc/dlls/triggers.cpp#L554-L555
https://github.com/YaLTeR/OpenAG/blob/061c06cfb5cc0e837c4063aa4dcedd9fe7d286bc/dlls/triggers.cpp#L1767-L1771

Register showtriggers as client command

---

cl_dll/CMakeLists.txt
cl_dll/cdll_int.cpp
cl_dll/hud.cpp
cl_dll/hud.h
cl_dll/hud_redraw.cpp
cl_dll/hud_strafeguide.cpp
cl_dll/hud_strafeguide.h
cl_dll/view.cpp

This was suggested before in #53. Basically, the center of the bar tells you whether you're accelerating (green), decelerating (red), or neither (white). Note that this doesn't take into account ground friction (yet).
`hud_strafeguide 1` to enable. `hud_strafeguide_fov`, `hud_strafeguide_height`, `hud_strafeguide_size` to manipulate.
I don't think this is anywhere near as useful as the Defrag HUDs people use, unless you're a strafing god you'll likely be almost always stuck at the edge between green and white. Suggestions on how to improve this are welcome, this is more of a prototype than anything else. I might add an indicator for the region of maximum acceleration, that could make it more useful at least for circle jumping.
But at least it looks cool.

Strafing HUD

---

cl_dll/StudioModelRenderer.cpp

Allows to draw absbox of entities in hardware mode, could be used for some of research.
That mode been added for SW a long time ago: https://github.com/YaLTeR/OpenAG/blob/e5bea9eba6836a2d9a8436f3b8103ef7d74a717e/cl_dll/StudioModelRenderer.cpp#L2137-L2140
... but for HW rendering it probably forgotten to add.

Added r_drawentities 5 for hardware rendering

---

cl_dll/input.cpp

Fix +ducktap that you weren't able to interfere in "ducking" process, now its working like +bxt_tas_ducktap

Ducktap fix

---

cl_dll/hud.cpp
cl_dll/hud.h

Hello.
**Motivation:**
This is useful against `play_team` and `play_close` "spamming" _[quotation marks because each sound gets replaced by the previous one]_ both of which send `PlaySound` UserMsg to players on your team and players on your team that are close to you, respectively. While this can be useful for normal DM for e.g. notifying about dropping weapons to your teammates with a specific sound, etc. it can get annoying on HLKreedz and other gamemodes, therefore this PR introduces a cvar to toggle being bombarded with sounds.
**Video:**
https://user-images.githubusercontent.com/5108747/157968525-dd9c54cf-2300-4e3d-80ee-63c6722c3a59.mp4
**What this disables:**
Just `play_team` and `play_close`, the usermsg isn't used anywhere else in the ServerDLL for any other sounds.
Proof:
user …

Added cl_team_sounds_volume

---

cl_dll/StudioModelRenderer.h

To make openag more binary compatible with original hl1 client

StudioModelRenderer: Move new methods to end of virtual table

---

cl_dll/entity.cpp
cl_dll/hud.cpp
cl_dll/hud.h

(Some additional info on his use case is: 1) doesnt hide players on HLKZ when playin', 2) recorded POV demo, 3) got a good run, 4) wanted to render POV demo, but now the other player is visible on the demo 5) sadface 6) this pr)
* No FCVAR_ARCHIVE so ppl dont forget that they hid players and wonder "wtf where players at"

Added cl_hide_other_players

---

cl_dll/text_message.cpp

AG 6.7 sends a byte for these chat message types that we can use to ignore them

Make name/team change and game leave messages ignorable

---

cl_dll/hud_redraw.cpp

Can be useful for recording some HLKZ runs (because there is always chat output of run time/top in leaderboard)

Make hud_saytext draw even when hud_draw is 0

---

CMakeLists.txt

The client.so must be explicitly linked to libSDL2, just like valve/cl_dlls/client.so.
Related issue: https://github.com/YaLTeR/OpenAG/issues/181

Make sure the client is linked to libSDL2

---

cl_dll/hud.cpp
cl_dll/hud_settings.cpp
cl_dll/hud_watermark.cpp

Command to toggle the HUD watermark that displays upon connecting to a server. Default value is 1.

Add hud_watermark command
